language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libgd2-noxpm-dev libpcap-dev libexpat1-dev
  - cpanm Module::CPANfile
install:
  - cpanfile-dump --develop --recommends --suggests --with-all-features | grep -v Dist::Zilla | cpanm --notest
  - env PERL_CPANM_OPT=--notest ./devel/update-fatlib --upgrade-local
script: "perl Makefile.PL && env AUTHOR_TESTING=1 make test"
